# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-10 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotrana001', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kotrana001_Model',
            new_name='Kotrana001_Model001',
        ),
    ]
